version: 2

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

formats:
-   htmlzip
-   pdf

build:
    image: latest

python:
    version: 3.7
    install:
    -   requirements: docs/requirements_rtfd.txt
