[build-system]
requires = ['setuptools', 'setuptools_scm', 'wheel', 'numpy', 'Cython']
build-backend = 'setuptools.build_meta'

[tool.flit.metadata]
module = "trisicell"
author = "Farid Rashidi"
author-email = "farid.rsh@gmail.com"
description-file = "README.rst"
